-- SELECT 'DROP TABLE ', TABLE_NAME, 'CASCADE CONSTRAINTS;' from USER_TABLES;
-- SELECT 'DROP FUNCTION' ,OBJECT_NAME,';' FROM USER_PROCEDURES WHERE OBJECT_TYPE= 'FUNCTION';
-- SELECT 'DROP TRIGGER' ,OBJECT_NAME,';' FROM USER_PROCEDURES WHERE OBJECT_TYPE= 'TRIGGER';

DROP TABLE REGIAO CASCADE CONSTRAINT;
DROP TABLE BAIRRO CASCADE CONSTRAINT;
DROP TABLE CENTRAL_POMBOS CASCADE CONSTRAINT;
DROP TABLE COCO_POMBO CASCADE CONSTRAINT;
DROP TABLE TIPO_PESSOA CASCADE CONSTRAINT;
DROP TABLE INFORMANTE CASCADE CONSTRAINT;
DROP TABLE CELULAR CASCADE CONSTRAINT;
DROP TABLE INFORMA_COCO CASCADE CONSTRAINT;
DROP TABLE ZELADOR CASCADE CONSTRAINT;
DROP TABLE NOTIFICACAO_ZELADOR CASCADE CONSTRAINT;
DROP TABLE MATADOR_POMBOS CASCADE CONSTRAINT;
DROP TABLE NOTIFICACAO_MATADOR CASCADE CONSTRAINT;
DROP TABLE PESQUISADOR CASCADE CONSTRAINT;
DROP TABLE NOTIFICACAO_PESQUISADOR CASCADE CONSTRAINT;
DROP TABLE LABORATORIO CASCADE CONSTRAINT;
DROP TABLE AMOSTRA CASCADE CONSTRAINT;
DROP TABLE RELATORIO CASCADE CONSTRAINT;
DROP TABLE SENSOR_DENSIDADE_POMBO CASCADE CONSTRAINT;
DROP TABLE DADOS_DENSIDADE CASCADE CONSTRAINT;

DROP TYPE Historico_Zel_Pes_Linha FORCE;
DROP TYPE Historico_Zel_Pes_Table FORCE;
DROP TYPE Historico_Pesq_Full_Linha FORCE;
DROP TYPE Historico_Pesq_Full_Table FORCE;
DROP TYPE Historico_Matador_Linha FORCE;
DROP TYPE Historico_Matador_Table FORCE;
DROP TYPE Densidade_Regiao_Linha FORCE;
DROP TYPE Densidade_Regiao_Table FORCE;

DROP FUNCTION DENSIDADE_REGIAO;
DROP FUNCTION HISTORICO_MATADOR;
DROP FUNCTION HISTORICO_PESQUISADOR;
DROP FUNCTION HISTORICO_PESQUISADOR_FULL;
DROP FUNCTION HISTORICO_ZELADOR;

DROP SEQUENCE ID_Coco;
